// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwEkudE-yg8VPPBY1_0bPSNIDYFk8LVEw',
    appId: '1:695164154657:web:def8394ded8dd213304460',
    messagingSenderId: '695164154657',
    projectId: 'hackathon-zeladoria',
    authDomain: 'hackathon-zeladoria.firebaseapp.com',
    storageBucket: 'hackathon-zeladoria.firebasestorage.app',
    measurementId: 'G-LSQXR5HREW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7pLC8v7FIQfqgt6iVBru1aNH5V0XmWQ',
    appId: '1:695164154657:android:e0035df9bcfd86e6304460',
    messagingSenderId: '695164154657',
    projectId: 'hackathon-zeladoria',
    storageBucket: 'hackathon-zeladoria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF42-BP7w4gzZNAX8b6Tm8quWYQfQFFwc',
    appId: '1:695164154657:ios:727ff4c3b3140700304460',
    messagingSenderId: '695164154657',
    projectId: 'hackathon-zeladoria',
    storageBucket: 'hackathon-zeladoria.firebasestorage.app',
    iosBundleId: 'com.hackathon.app',
  );
}
